name: Build and Push Patient Docker Image to ECR

on:
  push:
    branches:
      - main  # or your branch

jobs:
  build-and-push-patient:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image for patient
        run: |
          IMAGE_URI="922718141448.dkr.ecr.eu-north-1.amazonaws.com/patient:latest"
          docker build -t $IMAGE_URI .

      - name: Push Docker image to ECR
        run: |
          IMAGE_URI="922718141448.dkr.ecr.eu-north-1.amazonaws.com/patient:latest"
          docker push $IMAGE_URI
